Updates for Modern 7.2
apsislabs/rails_starter pull request #58
Opened 2024-10-10 20:57 UTC by wkirby

2024-10-11 17:53 UTC, egreer commented on Dockerfile
> +ENV CHROME_PATH="/usr/lib/chromium/"
Can remove chomium for sure

2024-10-11 17:53 UTC, egreer commented on Dockerfile
> +RUN gem update --system && gem install bundler:2.3.25
Should upgrade bundler to latest version

2024-10-11 17:53 UTC, egreer commented on Dockerfile
> +    && npm install -g pm2@4.5.6
Drop font libraries, `pandoc`, `chrome`, 

Do we need to upgrade `postgresql13` or still latest library?

2024-10-11 17:53 UTC, egreer commented on Dockerfile
> +COPY ./server $APP_HOME/
Change these all from `./server`

2024-10-11 17:53 UTC, egreer commented on Dockerfile
> +RUN find lib/assets/fonts -name '*.ttf' -exec ln '{}' /usr/share/fonts/ \;
Drop this

2024-10-11 17:53 UTC, egreer commented on Gemfile
> -  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
Byebug dropped for debug?

2024-12-19 19:12 UTC, egreer approved these changes

2025-08-25 13:47 UTC, egreer requested changes
Just a few updates

2025-08-25 13:47 UTC, egreer commented on Dockerfile.optimized
> +# Multi-stage build for better caching and smaller images
@wkirby Why don't we just use this as the normal docker file?

2025-08-25 13:47 UTC, egreer commented on .rubocop.yml
> +inherit_gem: { rubocop-rails-omakase: rubocop.yml }
Is there a reason we dropped prettier? And it looks like `omakase` styling is already included in rubocop by default according to their install instructions
https://github.com/rails/rubocop-rails-omakase?tab=readme-ov-file#installation

2025-08-25 13:47 UTC, egreer commented on Gemfile
> +  gem "rubocop-rails-omakase", require: false
Styling inconsistency in here did ew drop prettier?

2025-08-25 13:47 UTC, egreer commented on config/application.rb
> +module App2
We should probably rename this back to `RailsStarter`. There are a couple other references too.

2025-08-25 13:47 UTC, egreer commented on config/database.yml
> +    pool: 5
Lets set the connection pool to an environment variable that can be controlled centrally in `application.rb` .

Database.yml:
```yml
pool: <%= Rails.configuration.x.db_connection_pool %>
```

Application.rb:

```rb
    config.x.default_web_concurrency = Rails.env.production? ? ((Concurrent.processor_count * 2) + 1) : 0
    config.x.web_concurrency =
      (ENV.fetch('APP_CONCURRENCY', config.x.default_web_concurrency).presence || config.x.default_web_concurrency).to_i
    config.x.max_threads = ENV.fetch('RAILS_MAX_THREADS', 5).to_i
    config.x.min_threads = ENV.fetch('RAILS_MIN_THREADS', config.x.max_threads)

    # pool should always be >= (Puma) * RAILS_MAX_THREADS)
    config.x.db_connection_pool = config.x.max_threads * [config.x.web_concurrency, 1].max
```

In puma.rb:
```ruby
max_threads_count = Rails.configuration.x.max_threads
min_threads_count = Rails.configuration.x.min_threads
threads min_threads_count, max_threads_count

workers Rails.configuration.x.web_concurrency
```

Probably a similar change in `config/queue.yml` although I haven't looked into the values

2025-08-25 17:09 UTC, wkirby commented on .rubocop.yml
> +inherit_gem: { rubocop-rails-omakase: rubocop.yml }
Well this is claude being dumb. I was trying to switch to standardrb, but I think it interpreted that as "standard rubocop"

2025-08-28 13:18 UTC, egreer approved these changes

2025-09-09 15:01 UTC, merged